version: "3.7"
services:
  my-app:
    image: 357067782476.dkr.ecr.eu-central-1.amazonaws.com/my-app:1.0.5
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
